### ISSUE TITLE
Remove conditional define when optional dependency leaves a project

### ISSUE THREAD

**Issue by amirebrahimi** [Unity-Technologies/ConditionalCompilationUtility#3]
This can likely be fixed by using an AssetPostprocessor or the [CompilationPipeline](https://docs.unity3d.com/2017.3/Documentation/ScriptReference/Compilation.CompilationPipeline.html) (requires 2017.3 or later).

CCU will still be in memory before the project recompiles and could makes this fix before the compilation, so it doesn't leave the project in a broken state.

**Comment by Dorgam** [comment]
Hi,

Any updates on this?

I really need to remove the defines if I uninstall a plugin. Any way to achieve that?

Thank you.

**Comment by amirebrahimi** [comment]
Added with b3523ea
