### ISSUE TITLE
Unable to get CCU to define a scripting symbol when a package is installed. Am I doing something wrong? (Link to demo in description)

### ISSUE THREAD

**Issue by binarynate** [Unity-Technologies/ConditionalCompilationUtility#4]
Hello, and thank you ahead of time for your help! I'm an [Asset Store publisher](https://assetstore.unity.com/publishers/40309) and I'd like to use CCU in order to be able to conditionally include code only when the Oculus XR plugin is installed. However, I haven't been successful in achieving this yet. [Here is a tiny example project](https://github.com/BinaryNate/UnityCcuTest) that I created to demonstrate my approach. Its README describes the approach and links to its [Test.cs](https://github.com/BinaryNate/UnityCcuTest/blob/master/Assets/Test.cs) script, which demonstrates that CCU isn't detecting that the Oculus XR plugin is installed. Can you please take a look at [Test.cs](https://github.com/BinaryNate/UnityCcuTest/blob/master/Assets/Test.cs) and tell me if you see something that I'm doing wrong? Thanks!

**Comment by amirebrahimi** [comment]
Hi @BinaryNate,

Thank you for putting together an easy to follow test project.
At first glance it looks like all you need is to specify a specific class in the `Unity.XR.Oculus` namespace. Perhaps try:

[assembly: OptionalDependencyAttribute("Unity.XR.Oculus.OculusLoader", "OCULUS_XR_INSTALLED")]

and let me know if that works?

**Comment by binarynate** [comment]
Thank you so much for your help, @amirebrahimi ! That fixed the issue.
